In [12]:
import pandas 

dt = {

'Product A':[27,15,34,22,27,13,21],

'Product B':[56,51,41,55,49,56,44],

'Product C':[32,22,19,37,32,54,31],

'Product E':[21,40,17,26,31,33,29],

'Product F':[44,32,25,25,44,40,38]

}



label = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

sales  = pandas.DataFrame(dt,  label)

sales

           Product A  Product B  Product C  Product E  Product F
Monday            27         56         32         21         44
Tuesday           15         51         22         40         32
Wednesday         34         41         19         17         25
Thursday          22         55         37         26         25
Friday            27         49         32         31         44
Saturday          13         56         54         33         40
Sunday            21         44         31         29         38